### ISSUE TITLE
OpenJML and JMLUnitNG don't work with the diamond operator

### ISSUE THREAD

**Issue by NikolaRaevski** [OpenJML/OpenJML#448]
We are working on evaluation of JML's potential in large scale projects. Working with OpenJML &  JMLTestNG, we bumped into the following bug - the compiler doesn't work with the diamond operator introduced in java 1.7, nor does the JMLUnitNG, it leads to "illegal start of type" JML error:

```
.../Example.java:9: error: illegal start of type
    private List<String> list = new ArrayList<>();
                                              ^

    at org.jmlspecs.jmlunitng.JMLUnitNG.processAllCompilationUnits(JMLUnitNG.java:527)
    at org.jmlspecs.jmlunitng.JMLUnitNG.run(JMLUnitNG.java:414)
    at org.jmlspecs.jmlunitng.JMLUnitNG.main(JMLUnitNG.java:177)

```

Of course it works fine with pre-Java 1.7 generics:
    `private List<String> list = new ArrayList<String>();`

Is there a better working version?

**Comment by davidcok** [comment]
This would have been a JDK problem. Not sure when it was fixed, but it is OK now in JDK 8.

**Comment by MikeRawding** [comment]
I have been seeing this issue as well.  OpenJML 0.8.8, Eclipse neon.2, Java 8.  The following fails typecheck:

```
import java.util.ArrayList;

public class Main {
    public static void main(String[] args) {
        ArrayList<String> list = new ArrayList<>();
    }
}
```


> [0.00] Executing openjml on Main.java
(C:/jml/eclipse-workspace/Diamond/src/Main.java:5) [0] illegal start of type
		ArrayList<String> list = new ArrayList<>();
^
C:\jml\eclipse-workspace\Diamond\src\Main.java:5: error: illegal start of type
		ArrayList<String> list = new ArrayList<>();
		                                       ^
[0.45] Completed with errors

Using Java 6 syntax works as mentioned above.

**Comment by jsinglet** [comment]
Maybe we should merge in the recent work on JDK 8?  We may be slightly behind if there have been fixes since we pulled.

**Comment by davidcok** [comment]
Agreed - because lambda operations don't work completely either.
- David

**Comment by davidcok** [comment]
If you can find the source code zip or tar file let me know -- the jdk8u site is not very helpful in this regard.Problems with lambdas are impeding work on another project, so I'd like to move on this quickly.- David

**Comment by jsinglet** [comment]
I can do it tonight if you like.

**Comment by jsinglet** [comment]
@davidcok Take a look at the releases here: http://hg.openjdk.java.net/jdk8u/jdk8u-dev/langtools/tags

Which one do you want to update to?

**Comment by davidcok** [comment]
The most recent public, I expect : 121-b13

**Comment by davidcok** [comment]
Great

**Comment by davidcok** [comment]
John - The process I would imagine here is something like

a) merge master back to the jdk8u branchb) commit the jdk8u-121-b13 release as a replacement for the current head of the jdk8u vendor directoryc) merge the jdk8u vendor changes back to the OpenJDK jdk8u branchd) do all the debugging and merge conflict resolution in OpenJDK and OpenJML on the jdk8u branche) merge jdk8u back to master

But as these are not all different branches, I'm not sure we are set up properly to do this -- step (c) in particular.  The OpenJDK folder is supposed to be a copy of vendor with changes needed to support openjml -- with the goal of those changes being as few as possible.
Remind me how this works on GitHub with our current branch structure. DO we need to take the time to clean this up so that it works easily in the future?

**Comment by jsinglet** [comment]
@davidcok working on the merge now. I've merged master back into jdk8u and created a new local branch to work on the merge. The process is essentially:

```shell
git clone https://github.com/OpenJML/OpenJML.git
git checkout jdk8u
git merge master
git push
```

This brings jdk8u up to date with master (and of course there are no conflicts). 

```shell
git checkout -b jdk8u-03-16-2017-merge
git subtree pull --prefix OpenJDK/trunk/langtools https://github.com/OpenJML/jdk8u-dev-langtools refs/tags/jdk8u121-b13
```

This starts a merge from the jdk8u121-b13 release. 

I'm working on it now but there are quite a few conflicts. They are easy to resolve (obvious) but I think I can get through it today. If you want to work on it as well you can replicate my work with the commands above.

**Comment by davidcok** [comment]
Thanks - if you get to the point of conflicts you can't resolve - find a way to commit anyway and point me to the them. There will probably be even more to resolve when we tgry running tests.
- David
